version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -f debug/Dockerfile -t $DOCKER_USERNAME/debug:$TAG ./debug/
      - run: docker push $DOCKER_USERNAME/debug:$TAG
      - run: docker build -f fargate-ssm/Dockerfile -t $DOCKER_USERNAME/fargate-ssm:$TAG ./fargate-ssm/
      - run: docker push $DOCKER_USERNAME/fargate-ssm:$TAG
    environment:
      TAG: latest
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
